# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ErezAvital.NetworkSpeedTrayMonitor
PackageVersion: 1.0.1
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/erez-c137/NetSpeedTray/releases/download/v1.0.1/NetSpeedTray-Setup.exe
  InstallerSha256: E4B9F73D1DCEB1459CB2C7E5410200A974E1B7234DAF9A1BA0EFDABA77FE0DB3
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-02-21
